### ISSUE TITLE
build-with-apple.sh is broken because ios simulator architectures have changed

### ISSUE THREAD

**Issue by webern** [webern/mx#119]
https://github.com/webern/mx/runs/1766105028?check_suite_focus=true

Edit: the issue occurs when we try to create a fat binary that includes both iOS and iOS Simulator architectures. This used to mean we were combining i386 with arm64 (and whatever else). Now maybe the iOS Simulator runs with arm64? Maybe it depends on what your silicon is?

**Comment by CoderAndCat** [comment]
I tried various methods to use mx in my iOS app. But the compilation fails. 
this is new error 
<img width="1410" alt="截屏2021-02-04 11 14 51" src="https://user-images.githubusercontent.com/22518690/106839985-38655200-66da-11eb-9d42-89bd98ce917f.png">

**Comment by webern** [comment]
Is your project something that can be shared? It's been a while since I worked with iOS but I might be able to figure it out. The screenshot is not enough information.

**Comment by webern** [comment]
By the way, your problem is unrelated to this GH issue's continuous integration problem.
