### ISSUE TITLE
Help building the library

### ISSUE THREAD

**Issue by ArnyminerZ** [webern/mx#128]
Hi, I'm a beginner in c++, so please don't blame me if this is completely trivial.

I'm trying to compile the library using the following commands:
```shell
git clone https://github.com/webern/mx.git mx
mkdir build
cd build
cmake ../mx -DMX_BUILD_TESTS=off -DMX_BUILD_CORE_TESTS=off -DMX_BUILD_EXAMPLES=off
make -j6
```

And it compiles successfully, but I can't manage to find the build files. Where am I supposed to get the header files and all of that?
Thanks in advance.

**Comment by webern** [comment]
The libraries and binaries will be in the build directory. The headers are not copied during build, so they remain at their sourcecode location in the git repository at (I think) `Sourcecode/mx/api/`.

**Comment by ArnyminerZ** [comment]
Ooooh, okay, I get it. I'm trying to use the library now, thanks you very much 😇
