### ISSUE TITLE
Question about ordering of starts and stops for e.g. slurs

### ISSUE THREAD

**Issue by gergol** [webern/mx#139]
Currently, when I export a situation like this to music xml with `mx`
![image](https://user-images.githubusercontent.com/10432969/231823565-2dd9c952-bb28-4221-a872-357261df06cb.png)
the output looks like
```
<notations>
   <slur type="start" number="1"/>
   <slur type="stop" number="1"/>
</notations>
```
Unfortunately, this breaks the slurs completely when I import it into MuseScore.
If I flip the ordering of the start and stop elements above, it works fine. 

Quoting from https://www.w3.org/2021/06/musicxml40/musicxml-reference/data-types/start-stop-continue/ this seems to be even required by the MusicXML standard itself:

> When multiple elements with the same tag are used within the same note, their order within the MusicXML document should match the musical score order. For example, a note that marks both the end of one slur and the start of a new slur should have the incoming slur element with a type of stop precede the outgoing slur element with a type of start.

I'd open a PR that changes the export code such that stops always precede starts when they are on the same note.

**Comment by webern** [comment]
> the output looks like
> 
> ```
> <notations>
>    <slur type="start" number="1"/>
>    <slur type="stop" number="1"/>
> </notations>
> ```

What you are showing in this example is the *end* of the first slur and the *beginning* of the second slur, correct?
