### ISSUE TITLE
Cannot Compile with G++ due to GCC G++ bug

### ISSUE THREAD

**Issue by webern** [webern/mx#6]
This bug
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57158

Causes this error when compiling mx
/usr/include/c++/4.8/bits/vector.tcc:146:5: note:   candidate expects 2 arguments, 1 provided

**Comment by MartyLake** [comment]
FYI, this bug is marked as fixed on bugzilla: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57158

**Comment by webern** [comment]
Closing because this ancient gcc bug is surely gone from the world.
