### ISSUE TITLE
[feature] mx::api NonTraditionalKey equivalent

### ISSUE THREAD

**Issue by p-groarke** [webern/mx#70]
We've discussed about this in the past, and I've found mixing `mx::core` with `mx::api` to be a pain! :)

So, I'm just adding this here in case someday you'd want to add this feature to `mx::api`.

Cheers

**Comment by webern** [comment]
If you'd rather I finish up with my branch (I think it's ready) then I can do that instead.

**Comment by p-groarke** [comment]
Up to you. If you already have the feature up and working + tested, you can just merge that and close my PR. I won't be offended by it ;)
