### ISSUE TITLE
NonTraditional key : C key

### ISSUE THREAD

**Issue by p-groarke** [webern/mx#89]
By using the `KeyComponent` vector `empty` to check whether a key is in non-traditional mode, it makes it impossible to create C keys.

**Comment by p-groarke** [comment]
Eh, its not a big deal.

**Comment by webern** [comment]
I was going to ask for more detail because I didn't understand. If it's important then provide the MusicXML that you are trying to create and the mx code that fails to provide it. Thanks!

**Comment by p-groarke** [comment]
The main problem I'm seeing is musescore's musicxml key support is abysmal.

Try this to understand : make a C key using the NonTraditional api.

User story : The user is writing generic code that uses non traditional keys to build keys. He wants to make a C key.

**Comment by webern** [comment]
OK, I might counter that using a non traditional key to represent, for example, C Major, is 'doing it wrong'. I would expect many applications to be confused by that. I think that some logic should be used when authoring MusiXML to say "if this is a traditional key" then "use the traditional key api". 

Another way of saying that is to say that the non-traditional key element is only intended for key signatures that cannot be represented with the traditional key element. At least that is my interpretation.

I would think an empty non-traditional key element would be poorly understood by most applications.

Much of MusicXML is interpreting the schema, but Michael Good is very responsive over here https://github.com/w3c/musicxml

**Comment by p-groarke** [comment]
Like I said, it isn't a big deal and if musescore worked as it should, it wouldn't be a problem. musescore doesn't cancel non-traditional keys when they are followed by a traditional fifth = 0 key. But it works for other traditional keys.

I don't know who Michael Good is, but I can assure you the problems lies with musescore, not musicxml. The fact that mx outputs a traditional fifth C key instead of non-traditional is super minor, I just wasn't expecting that.

**Comment by webern** [comment]
OK, sorry to hear that MuseScore has a bug. Michael Good is the author of MusicXML.
